TELEGRAM_TOKEN = "8869758028:AAHtKdxdzNTJabCZAFYyynLoLj4pDppJvMM
Iran"
TELEGRAM_CHAT_ID = "0"
MIN_24H_VOLUME_USD = 20_000_000
TOP_PAIRS = [
"BTC/USDT",
"ETH/USDT",
"SOL/USDT",
"BNB/USDT",
"ADA/USDT",
"AVAX/USDT",
"LINK/USDT",
"DOT/USDT",
"SUI/USDT",
"APT/USDT",
"LTC/USDT",
"MATIC/USDT"
]
TIMEFRAME = "1h"
MIN_RR_RATIO = 2.0
REQUIRED_CONFLUENCE_SCORE = 4
RSI_PERIOD = 14
EMA_FAST = 50
EMA_SLOW = 200
ATR_PERIOD = 14
